name: Build Packages

env:
FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
push:
branches: [ main ]

pull_request:

workflow_dispatch:

jobs:

linux-appimage:
runs-on: ubuntu-24.04

```
steps:
  - uses: actions/checkout@v5

  - name: Install Dependencies
    run: |
      sudo apt-get update

      sudo apt-get install -y \
        cmake \
        ninja-build \
        build-essential \
        qt6-base-dev \
        qt6-charts-dev \
        qt6-tools-dev \
        libqt6sql6-sqlite \
        patchelf

  - name: Install AppImageTool
    run: |
      wget -O appimagetool \
        https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage

      chmod +x appimagetool
      sudo mv appimagetool /usr/local/bin/

  - name: Configure
    run: cmake --preset github-linux-appimage

  - name: Build
    run: cmake --build --preset github-linux-appimage

  - name: Package
    run: |
      cd build/github-linux-appimage
      cpack

  - name: Upload AppImage
    uses: actions/upload-artifact@v4
    with:
      name: FitlyzerC-AppImage
      path: |
        **/*.AppImage
```

windows-nsis:
runs-on: windows-2025

```
steps:
  - uses: actions/checkout@v5

  - uses: jurplel/install-qt-action@v4
    with:
      version: '6.9.0'

  - name: Configure
    run: cmake --preset github-windows-nsis

  - name: Build
    run: cmake --build --preset github-windows-nsis

  - name: Package
    run: |
      cd build/github-windows-nsis
      cpack -C Release

  - name: Upload Installer
    uses: actions/upload-artifact@v4
    with:
      name: FitlyzerC-Windows-Installer
      path: |
        **/*Setup*.exe
```

macos-dmg:
runs-on: macos-15

```
steps:
  - uses: actions/checkout@v5

  - uses: jurplel/install-qt-action@v4
    with:
      version: '6.9.0'

  - name: Configure
    run: cmake --preset github-macos-dmg

  - name: Build
    run: cmake --build --preset github-macos-dmg

  - name: Package
    run: |
      cd build/github-macos-dmg
      cpack

  - name: Upload DMG
    uses: actions/upload-artifact@v4
    with:
      name: FitlyzerC-macOS-DMG
      path: |
        **/*.dmg
```
